/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.Conexao;
import Controle.VoluntarioDAO;
import Modelo.Voluntario;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author m-oli
 */
public class Relatorio extends javax.swing.JDialog {

    /**
     * Creates new form Relatorio
     */
    public Relatorio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContainerCadastro = new javax.swing.JPanel();
        jTextFieldP_Nome = new javax.swing.JTextField();
        jLabelP_Nome = new javax.swing.JLabel();
        jLabelPX = new javax.swing.JLabel();
        jTextFieldPX = new javax.swing.JTextField();
        jTextFieldP_Cor = new javax.swing.JTextField();
        jLabelP_Cor = new javax.swing.JLabel();
        jTextFieldP_Preco = new javax.swing.JTextField();
        jLabelP_Preco = new javax.swing.JLabel();
        jButtonCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelContainerCadastro.setBackground(new java.awt.Color(153, 153, 255));

        jLabelP_Nome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelP_Nome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelP_Nome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelP_Nome.setText("P Nome");

        jLabelPX.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPX.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPX.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPX.setText("PX");

        jTextFieldPX.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPXFocusLost(evt);
            }
        });

        jLabelP_Cor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelP_Cor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelP_Cor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelP_Cor.setText("P Cor");

        jLabelP_Preco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelP_Preco.setForeground(new java.awt.Color(255, 255, 255));
        jLabelP_Preco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelP_Preco.setText("P Preço");

        javax.swing.GroupLayout jPanelContainerCadastroLayout = new javax.swing.GroupLayout(jPanelContainerCadastro);
        jPanelContainerCadastro.setLayout(jPanelContainerCadastroLayout);
        jPanelContainerCadastroLayout.setHorizontalGroup(
            jPanelContainerCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerCadastroLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanelContainerCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelP_Nome)
                    .addComponent(jLabelP_Cor)
                    .addComponent(jLabelP_Preco)
                    .addComponent(jLabelPX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelContainerCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldP_Nome, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addComponent(jTextFieldP_Cor, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldP_Preco, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPX))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanelContainerCadastroLayout.setVerticalGroup(
            jPanelContainerCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerCadastroLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelContainerCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPX)
                    .addComponent(jTextFieldPX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelContainerCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldP_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelP_Nome, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanelContainerCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelP_Cor)
                    .addComponent(jTextFieldP_Cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelContainerCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldP_Preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelP_Preco))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jButtonCadastrar.setBackground(new java.awt.Color(153, 153, 255));
        jButtonCadastrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCadastrar.setForeground(new java.awt.Color(0, 0, 255));
        jButtonCadastrar.setText("RELATÓRIO");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(430, Short.MAX_VALUE)
                .addComponent(jButtonCadastrar)
                .addGap(57, 57, 57))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jPanelContainerCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(39, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(281, Short.MAX_VALUE)
                .addComponent(jButtonCadastrar)
                .addGap(61, 61, 61))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(102, 102, 102)
                    .addComponent(jPanelContainerCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(103, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPXFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPXFocusLost
        Voluntario voluntario = new VoluntarioDAO().getUsuarioCompleto(this.jTextFieldPX.getText());

        if(voluntario != null){
            this.jTextFieldPX.setText(""+voluntario.getPX());
            this.jTextFieldP_Nome.setText(""+voluntario.getP_Nome());
            this.jTextFieldP_Cor.setText(""+voluntario.getP_Cor());
            this.jTextFieldP_Preco.setText(""+voluntario.getP_Preco());

        }

    }//GEN-LAST:event_jTextFieldPXFocusLost

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
       
        Connection conn = Conexao.getInstance().getConnection();
        
      //  Connection conn = Conexao.getInstance().getConnection();
        JasperPrint print = null;        
        
        try {
          print= JasperFillManager.fillReport("C:\\Users\\m-oli\\OneDrive\\Documentos\\NetBeansProjects\\PROVA\\SistemaCompras\\src\\Visao\\report1.jasper", null,conn); //utilize o arquivo .jasper, não o jrxml.
           
        } catch (Exception e) {
            System.out.println("Erro"+e);
        }
        
      JasperViewer view = new JasperViewer(print,false);
      view.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Relatorio dialog = new Relatorio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    //Classes
        private void inicializaCamposETabelas() {
       // getDataTableAlunos();
        limpaCampos();
    }
    
    private void limpaCampos() {
        this.jTextFieldPX.setText("");
        this.jTextFieldP_Nome.setText("");
        this.jTextFieldP_Cor.setText("");
        this.jTextFieldP_Preco.setText("");
        this.jTextFieldPX.requestFocus();
        //setStatComponents("inicio");
    }
    
        private ArrayList <Voluntario> getDataTableVoluntario() {
        int i;
 //       DefaultTableModel model=(DefaultTableModel)jTBLAlunos.getModel();
        // atribui 0 linhas à coluna
    //    model.setNumRows(0);
        // atribui um tamanho fixo a coluna codigo
      //  jTBLAlunos.getColumnModel().getColumn(0).setPreferredWidth(2);
        ArrayList<Voluntario> listVoluntarios = new ArrayList<Voluntario>();
        listVoluntarios = new VoluntarioDAO().getListaVoluntario();
        //adiciona alunos as tabelas
       // for (i=0;i<=listVoluntarios.size()-1;i++){
        //    model.addRow(new Object[]{listAlunos.get(i).getCodigo(),listAlunos.get(i).getNome()});
        //}
        return listVoluntarios;
    }
    
     private Voluntario getDadosFrameVoluntario(){
        Voluntario voluntario = new Voluntario();
        
        voluntario.setPX(this.jTextFieldPX.getText());
        voluntario.setP_Nome(this.jTextFieldP_Nome.getText());
        voluntario.setP_Cor(this.jTextFieldP_Cor.getText());
        voluntario.setP_Preco(this.jTextFieldP_Preco.getText());
        
       
       
//        voluntario.setEmail(this.jTextFieldPX.getText());
//        voluntario.setSenha(this.jTextFieldP_Nome.getText());
//        voluntario.setNome(this.jTextFieldP_Cor.getText());
//        voluntario.setTelefone(this.jTextFieldP_Preco.getText());
        
        return voluntario;
    }
    
    
    //Fim

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JLabel jLabelPX;
    private javax.swing.JLabel jLabelP_Cor;
    private javax.swing.JLabel jLabelP_Nome;
    private javax.swing.JLabel jLabelP_Preco;
    private javax.swing.JPanel jPanelContainerCadastro;
    private javax.swing.JTextField jTextFieldPX;
    private javax.swing.JTextField jTextFieldP_Cor;
    private javax.swing.JTextField jTextFieldP_Nome;
    private javax.swing.JTextField jTextFieldP_Preco;
    // End of variables declaration//GEN-END:variables
}
